parameters:
    gnutix_library.loader.xml_file_loader.class: Gnutix\Library\Loader\XmlFileLoader
    gnutix_library.loader.yaml_file_loader.class: Gnutix\Library\Loader\YamlFileLoader
    gnutix_library.library_factory.xml_library_factory.class: Gnutix\Library\LibraryFactory\XmlLibraryFactory
    gnutix_library.library_factory.yaml_library_factory.class: Gnutix\Library\LibraryFactory\YamlLibraryFactory
    gnutix_library.twig.library_extension.class: Gnutix\Library\Twig\Extension\LibraryExtension

services:
    gnutix_library.library:
        class: Gnutix\Library\LibraryInterface
        factory_service: gnutix_library.library_factory
        factory_method: getLibrary

    gnutix_library.loader:
        alias: gnutix_library.loader.yaml_file_loader

    gnutix_library.library_factory:
        alias: gnutix_library.library_factory.yaml_library_factory

    gnutix_library.loader.xml_file_loader:
        class: %gnutix_library.loader.xml_file_loader.class%
        arguments: [%gnutix_library.source_file_path%]

    gnutix_library.library_factory.xml_library_factory:
        class: %gnutix_library.library_factory.xml_library_factory.class%
        arguments: [@gnutix_library.loader.xml_file_loader]

    gnutix_library.loader.yaml_file_loader:
        class: %gnutix_library.loader.yaml_file_loader.class%
        arguments: [%gnutix_library.source_file_path%]

    gnutix_library.library_factory.yaml_library_factory:
        class: %gnutix_library.library_factory.yaml_library_factory.class%
        arguments: [@gnutix_library.loader.yaml_file_loader]

    gnutix_library.twig.library_extension:
        class: %gnutix_library.twig.library_extension.class%
        tags:
            - { name: twig.extension }
