---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the drifter README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
   - parameters.yml
  sudo: no

  roles:
    - { role: base }
    - { role: php-fpm, nginx_site_template: 'symfony2-site.j2' }
    - { role: composer }
    - { role: nodejs }

  tasks:
    - name: Install JSHint globally
      npm: name=jshint global=yes
      sudo: yes

    - name: Install Bower globally
      npm: name=bower global=yes
      sudo: yes

    - name: install backend vendors
      shell: cd {{ project_directory }} && composer.phar --quiet install

    - name: install frontend vendors
      shell: cd {{ project_directory }} && bower install
