parameters:
    gnutix_library.classes_map:
        author: Gnutix\Library\Model\Author
        book: Gnutix\StarWarsLibrary\Model\Book
        category: Gnutix\Library\Model\Category
        editor: Gnutix\Library\Model\Editor
        language: Gnutix\Library\Model\Language
        library: Gnutix\StarWarsLibrary\Model\Library
        release: Gnutix\Library\Model\Release
        series: Gnutix\Library\Model\Series
        format: Gnutix\Library\Model\Format
        owner: Gnutix\Library\Model\Owner
        chronologicalMarker: Gnutix\StarWarsLibrary\Model\ChronologicalMarker
        era: Gnutix\StarWarsLibrary\Model\Era
    gnutix_library.library_factory.xml_library_factory.class: Gnutix\StarWarsLibrary\LibraryFactory\XmlLibraryFactory
    gnutix_library.library_factory.yaml_library_factory.class: Gnutix\StarWarsLibrary\LibraryFactory\YamlLibraryFactory
    gnutix_library.twig.star_wars_extension.class: Gnutix\StarWarsLibrary\Twig\Extension\StarWarsExtension

services:
    gnutix_library.twig.star_wars_extension:
        class: %gnutix_library.twig.star_wars_extension.class%
        tags:
            - { name: twig.extension }
