twig:
    strict_variables: true
    cache: false
    paths:
        - "%kernel.project_dir%/templates"
    globals:
        library: "@gnutix_library.library"

gnutix_library:
    source_file_path: "%kernel.project_dir%/data/library.yml"
